// Code generated by goctl. DO NOT EDIT.
package types

type GetTopicRequest struct {
	UserName string `json:"user_name"`
}

type Topic struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	FileUrl     string `json:"file_url"`
}

type GetTopicResponse struct {
	TopicList []Topic `json:"topic_list"`
}
