// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	SessionID             int64  `json:"session_id"`
	AccessToken           string `json:"access_token"`
	AccessTokenExpiresAt  int64  `json:"access_token_expires_at"`
	RefreshToken          string `json:"refresh_token"`
	RefreshTokenExpiresAt int64  `json:"refresh_token_expires_at"`
}

type InfoRequest struct {
}

type InfoResponse struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResponse struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type DeleteRequest struct {
}

type DeleteResponse struct {
}

type UpdateRequest struct {
	Password string `json:"password"`
	Email    string `json:"email"`
}

type UpdateResponse struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}
